<a href="https://colab.research.google.com/github/Yikang1020/Statistics-for-neuroscience/blob/main/pandas%26numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy

In [2]:
import numpy as np

## argpartition()
argpartition() can find the index of the n maximum, and output the indexs.

In [97]:
# define a array
x = np.array([12, 10, 12, 0, 6, 8, 9, 1, 16, 4, 6, 0])
# extract the max 4 indexs
index_val = np.argpartition(x,-4)[-4:]
# sort the values
np.sort(x[index_val])

## allclose()

allclose() is to match two arrays.

In [100]:
# create two arrays
array1 = np.array([0.12,0.17,0.24,0.29])
array2 = np.array([0.13,0.19,0.26,0.31])
# with a tolerance of 0.1, it should return False:
print(np.allclose(array1,array2,0.1))
# with a tolerance of 0.2, it should return True:
print(np.allclose(array1,array2,0.2))

False
True


## clip()

clip() can keep an array in a interval.

In [102]:
# create an array
x = np.array([3, 17, 14, 23, 2, 2, 6, 8, 1, 2, 16, 0])
# keep the value in [2,5]
np.clip(x,2,5)

array([3, 5, 5, 5, 2, 2, 5, 5, 2, 2, 5, 2])

## extract()

extract() can obtain specific element. 

In [105]:
# create an array
x = np.random.randint(20, size=12)
# Divide by 2 and check if remainder is 1
cond = np.mod(x, 2)==1
# Acquire the array whose remainder is 1
print(np.extract(cond,x))
# Acquire the array between [3,15]
print(np.extract(((x<3)|(x>15)),x))


[11 17 15 11  5 13 19]
[17 16  0 19  0 18]


## where()

where() return the specific element meeting the requirement.

In [111]:
# Create an array
x = np.array([1,5,6,8,1,7,3,6,9])
# Where y is greater than 5, returns index position
print(np.where(x>5))
print(x[np.where(x>5)])
# First will replace the values that match the condition, 
# second will replace the values that does not
print(np.where(x>5, "Hit", "Miss"))

(array([2, 3, 5, 7, 8]),)
[6 8 7 6 9]
['Miss' 'Miss' 'Hit' 'Hit' 'Miss' 'Hit' 'Miss' 'Hit' 'Hit']


## percentile

percentile() can used to computate the nth percentile of specific axis.

In [115]:
# create the array
a = np.array([1,5,6,8,1,7,3,6,9])
# print the 50th percentile
print("50th Percentile of a, axis = 0 : ",np.percentile(a, 50, axis =0))
# create the array
b = np.array([[10, 7, 4], [3, 2, 1]])
# print the 30th percentile
print("30th Percentile of b, axis = 0 : ",np.percentile(b, 30, axis =0))

50th Percentile of a, axis = 0 :  6.0
30th Percentile of b, axis = 0 :  [5.1 3.5 1.9]


# pandas

## read_csv(nrows=n)

In [119]:
import io
import requests
import pandas as pd
# I am using this online data set just to make things easier for you guys
url = "https://raw.github.com/vincentarelbundock/Rdatasets/master/csv/datasets/AirPassengers.csv"
s = requests.get(url).content
# read only first 10 rows
df = pd.read_csv(io.StringIO(s.decode('utf-8')),
          nrows=10,
          index_col=0)

## map()

map() can map the values of `series` according to the input.

In [161]:
# create a dataframe
dframe = pd.DataFrame(np.random.randn(4, 3), 
            columns=list('bde'), 
            index=['India', 'USA', 'China', 'Russia'])
#compute a formatted string from each floating point value in frame
changefn = lambda x: '%.2f' % x
# Make changes element-wise
dframe['d'] = dframe['d'].map(changefn)

## apply()

map() can map the values of `dataframe` according to the input.

In [167]:
# max minus mix lambda fn
fn = lambda x: x.max()+x.min()
# Apply this on dframe that we've just created above
dframe.apply(fn)

b   -0.261621
d    2.180.02
e     0.61179
dtype: object

## isin()

isin() can select the specific line of specific row

In [168]:
# Using the dataframe we created for read_csv
filter1 = df["value"].isin([112]) 
filter2 = df["time"].isin([1949.000000])
df [filter1 & filter2]

time  value
1  1949.0    112

## copy()
copy() can dulipate the dataframe and the value dulipated cannot be changed.

In [176]:
# creating sample series 
data = pd.Series(['India', 'Pakistan', 'China', 'Mongolia'])
# Assigning issue that we face
data1= data
# Change a value
data1[0]='USA'
# Also changes value in old dataframe
print(data)
# To prevent that, we use creating copy of series 
new = data.copy()
# assigning new values 
new[1]='Changed value'
# printing data 
print(data) 

0         USA
1    Pakistan
2       China
3    Mongolia
dtype: object
0         USA
1    Pakistan
2       China
3    Mongolia
dtype: object


## select_dtypes()

select_dtypes() can return the subset of specific dayatype.

In [182]:
# We'll use the same dataframe that we used for read_csv
framex =  df.select_dtypes(exclude="float64")
print(framex)
framex =  df.select_dtypes(include="float64")
print(framex)

    value
1     112
2     118
3     132
4     129
5     121
6     135
7     148
8     148
9     136
10    119
           time
1   1949.000000
2   1949.083333
3   1949.166667
4   1949.250000
5   1949.333333
6   1949.416667
7   1949.500000
8   1949.583333
9   1949.666667
10  1949.750000


## pivot_table()

pivot_table() can adjust the row and line of raw table.

In [186]:
# Create a sample dataframe
school = pd.DataFrame({'A': ['Jay', 'Usher', 'Nicky', 'Romero', 'Will'], 
      'B': ['Masters', 'Graduate', 'Graduate', 'Masters', 'Graduate'], 
      'C': [26, 22, 20, 23, 24]})
# Lets create a pivot table to segregate students based on age and course
table = pd.pivot_table(school, 
             values ='A', 
             index =['B', 'C'],  
             columns =['B'], 
             aggfunc = np.sum, 
             fill_value="Not Available") 

print(table)
# table without columns
table = pd.pivot_table(school, 
             values ='A', 
             index =['B', 'C'],  
             aggfunc = np.sum, 
             fill_value="Not Available") 

print(table)

B                 Graduate        Masters
B        C                               
Graduate 20          Nicky  Not Available
         22          Usher  Not Available
         24           Will  Not Available
Masters  23  Not Available         Romero
         26  Not Available            Jay
                  A
B        C         
Graduate 20   Nicky
         22   Usher
         24    Will
Masters  23  Romero
         26     Jay
